[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 10000
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
SPRING_PROFILES_ACTIVE = "prod"
